# Agradecimientos {.unnumbered}

En primer lugar, agradezco a mi pareja Pamela García y su familia: Ana Muñoz, Luz Muñoz y Marina Véliz por brindarme apoyo incondicional para cumplir mis objetivos tanto personales como académicos. Ellos me han acogido con brazos abiertos en este complejo período y me han apoyado en perseguir y continuar con mis estudios. Me han brindado soporte económico y emocional para poder seguir adelante. Además, quiero agradecer a mi hija Isabel Vargas, que en los pocos días desde que llegó al mundo me ha traído mucho amor y alegría constante.

En segundo lugar, quiero agradecer a mi tutor Jonathan Acosta por el apoyo en el desarrollo del presente trabajo durante el magíster, desde el envío de sus clases de estadística espacial hasta las reuniones frecuentes y la explicación de varios conceptos, los cuales me permitieron familiarizarme y desarrollarme en una de las disciplinas que desde el pre-grado de Medicina Veterinaria he considerado muy interesante.


Además, agradezco a todos los docentes de la Pontificia Universidad Católica que me enseñaron durante el transcurso del Magíster: Pedro Ramos, Manuel Galea, Alejandro Jara, Ana María Araneda, Ricardo Aravena, Ricardo Olea, Joshua Kunst, y María José García por su tiempo y dedicación a la docencia.

Agradezco también a los ayudantes: Josefa Silva, Jesús Achire, Julio Ávila, Nixon Jerez, Bladimir Morales y Alonso Campos por las ayudantías realizadas y por su disposición a resolver todo tipo de dudas y consultas.


Agradezco a todos mis compañeros por el buen ambiente que se generó durante el programa, tanto a nivel de colaboración como en la comunicación entre los distintos grupos. 

Finalmente, agradezco a la Pontificia Universidad Católica por la oportunidad de haber realizado el magíster y por mantener un alto estándar de calidad y exigencia a nivel de docentes y estudiantes.